dimagi/langcodes

langs.json

http://manage.dimagi.com/default.asp?164010

add Krio to list of languages

---

langs.json

Tracked in [FB 168280](http://manage.dimagi.com/default.asp?168280)
Ping @millerdev

Added Diola and Pulaar languages

---

langs.json

http://www-01.sil.org/iso639-3/documentation.asp?id=dag
http://manage.dimagi.com/default.asp?181152

add 'dag' langcode

---

langs.json

http://manage.dimagi.com/default.asp?229661
@orangejenny

add Tandroy-Mafahaly

---

urls.py

make urls django 1.10 compatible

---

static/langcodes/html/langcodes.html

Followup for https://github.com/dimagi/langcodes/pull/8
@calellowitz

Static HTML should reference select2 not jQuery UI

---

urls.py

futurize . -w -f libfuturize.fixes.fix_absolute_import

---

__init__.py
views.py

add 'from __future__ import absolute_import' to all .py files

---

__init__.py

python-modernize . -w -f libmodernize.fixes.fix_dict_six

---

views.py

python-modernize . -w -f lib2to3.fixes.fix_ws_comma

---

views.py

python-modernize . -w -f libmodernize.fixes.fix_filter

---

__init__.py
urls.py
views.py

python-modernize . -w --future-unicode

---

__init__.py

use io.open

---

views.py

https://manage.dimagi.com/default.asp?280975#1517117
code allows the searching the language with name also

To allow search with language name

---

static/langcodes/js/langcodes.js

This code is a part of  migrating the sms/languages. its parent PR is https://github.com/dimagi/commcare-hq/pull/21695

enclosing langcode code in define

---

static/langcodes/html/langcodes.html
static/langcodes/js/langcodes.js

Sanity tested locally on app manager languages page.
@pr33thi / @Rohit25negi

upgrade select2 references from 3.4.5 to 3.5.2

---

langs.json

https://manage.dimagi.com/default.asp?283349
@millerdev 
edit on same lines as https://github.com/dimagi/langcodes/pull/20/

Add Gedeo and Korete

---

static/langcodes/html/langcodes.html
static/langcodes/js/langcodes.js

Part of https://github.com/dimagi/commcare-hq/pull/23754, should be merged at the same time.
@gbova / @millerdev / @Rohit25negi 
Depends on https://github.com/dimagi/langcodes/pull/28

Migrate select2

---

static/langcodes/js/langcodes.js

Same as https://github.com/dimagi/commcare-hq/pull/24515

Updated quietMillis to delay

---

langs.json

https://forum.dimagi.com/t/how-to-add-new-languages-to-the-app-which-does-not-exist-in-the-list/7759
https://iso639-3.sil.org/code/anu
First commit sorts some languages that were appended to the list

Anuak language

---

langs.json

See this ticket for the request https://dimagi.atlassian.net/browse/SAAS-14019

remove Walamo from language names for wal as it is no longer appropriate
